### ISSUE TITLE
Update infrastructure

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#12]
- Add monitor (return old one to Phil) 
- Add RAM

**Comment by lbergsten** [comment]
RAM added (still need monitor) and to change the commands to have appropriate VIs pop up

**Comment by hherde** [comment]
To be managed by BNL...

**Comment by zachschillaci27** [comment]
Dual-monitors now installed, external hard drive for calibration backups on its way
