### ISSUE TITLE
Address memory management issues, particularly wrt images

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#15]
Save images as they are collected, rather than in bulk later.

**Comment by hherde** [comment]
"CollectImages (SubVI).vi" now saves each image as it is collected, rather than waiting until the end. We might need to change image loading (currently pulls all images into an array; might want to call up individually)

**Comment by sciollalab** [comment]
Now loading images from file when they are processed, and then removing each one from memory as it is processed, rather than passing full arrays of images around -- greatly reduces the footprint
