### ISSUE TITLE
Arduino-based lighting and temperature monitoring

### ISSUE THREAD

**Issue by sciollalab** [sciollalab/BNL_ThermomechanicalStave#37]
- Circuit soldered to a breadboard, created as a daughter board for Arduino Uno 
- In the process of enclosing the whole unit in a box
- Will replace the GPIB-controlled lights and temperature readout

**Comment by hherde** [comment]
DONE. Finished with master branch commit 9159832c7de13e11f48b69d27d10eae6015925e5
