### ISSUE TITLE
VMP: "Good spot" indicator

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#44]
Change the "good spot" indicator tick mark to a large, green boolean which illuminates when the fiducial is detected in the centre (within tolerance)

Leave tweaking arrows enabled so that they still show direction of fiducial's displacement from centre

**Comment by sciollalab** [comment]
hherde: replaced the boolean in pull request #53

**Comment by zachschillaci27** [comment]
This has long been implemented
