### ISSUE TITLE
Vignetting autoanalysis for camera tilt angle calibration check 

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#5]

**Comment by sciollalab** [comment]
Catherine Nicoloff developing this. To be tested early next week

**Comment by hherde** [comment]
Catherine's code live on the Master Branch as of today. Added to Utils as a new folder; incorporated into ContinuouStageAndCameraV2 as a camera function

**Comment by hherde** [comment]
Resolved with pull request #32
