### ISSUE TITLE
Develop user instructions/begin documentation of code structure 

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#8]
Possibly via a Wiki? Start documenting the code's phases and philosophy. Add a section describing stave-specific features.

**Comment by sciollalab** [comment]
In progress (slowly) on the wiki tab. Also planning to provide doc files in the "Documentation" folder of the code directory

**Comment by sciollalab** [comment]
Closing this issue. We will use a Git Project to track the documentation status and open more specific Issue Requests.
