### ISSUE TITLE
Convert virtual map inputs to load from file

### ISSUE THREAD

**Issue by hherde** [sciollalab/BNL_ThermomechanicalStave#9]

**Comment by hherde** [comment]
Resolved using a Utils/Standalone -- [CreateStaveMapFromCalibration.vi](https://github.com/sciollalab/BNL_ThermomechanicalStave/blob/master/Utils/Standalone/CreateStaveMapFromCalibration.vi.) Unclear if that is sufficient.

**Comment by zachschillaci27** [comment]
Updated CreateStaveMapFromCalibration.vi to accommodate recent changes - outputs updated virtual map and calibration results file
